@startuml
hide empty members
class UnknownInterface {
}
class TestInterface {
+m_someMember : int
}
class TestClass {
+func()
+m_enumValue : TestEnum
+get()
+m_myInt : unsigned int
#m_structValue : TestStruct
#m_protectedInt : int
-someFunc()
-m_someVar : float
}
enum TestEnum {
One
Two
}
TestClass o-- TestEnum
class TestStruct {
+one : int
}
TestClass o-- TestStruct
TestClass .. TestInterface
TestClass .. UnknownInterface
@enduml