@startuml
class TestClass {
+m_enumValue : TestNamespace::TestClass::TestEnum
+get()
+m_myInt : unsigned int
#m_structValue : TestNamespace::TestClass::TestStruct
#m_protectedInt : int
-someFunc()
-m_someVar : float
}
enum TestEnum {
}
TestClass o-- TestEnum
struct TestStruct {
+one : int
}
TestClass o-- TestStruct
@enduml